In [2]:
import random
import numpy as np
import pickle
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
df = pd.read_csv('Knapsack-100items.csv')

In [11]:
values = df.p
weights = df.W

In [46]:
def init(population_size):
    return np.random.randint(2, size=(population_size, len(values)))
def objective_function_by_value(chromosome):
    sum = 0
    for i in range(len(chromosome)):
        sum += chromosome[i] * values[i]
    return sum

def objective_function_by_weight(chromosome):
    sum = 0
    for i in range(len(chromosome)):
        sum += chromosome[i] * weights[i]
    return -sum
    
def compute_fitness(chromosomes, objective_i):
    if objective_i == 0: # value
        fitness_function = objective_function_by_value
    elif objective_i == 1: # weight
        fitness_function = objective_function_by_weight
    
    fitness_batch = []
    for chromosome in chromosomes:
        fitness = fitness_function(chromosome)
        fitness_batch.append(fitness)
    return fitness_batch

def select_top_n(chromosomes, fitness, n):
    index = np.argsort(-fitness)
    return chromosomes[index[:n]]

def selection_within_subgroup(chromosomes, n):
    objective_i = np.random.randint(2)
    fitness = compute_fitness(chromosomes, objective_i)
    parents_subgroup = select_top_n(chromosomes, fitness, n)
    return parents_subgroup

def crossover(parent_1, parent_2):
    rand = np.random.randint(4)
    if rand == 0:
        child = parent_1
    elif rand == 1:
        child = parent_2
    elif rand == 2:
        child = np.concatenate((parent_1[:len(parent_1)/2], parent_2[len(parent_2)/2:]), axis=0)
    elif rand == 3:
        child = np.concatenate((parent_2[:len(parent_2)/2], parent_1[len(parent_1)/2:]), axis=0)
    return child

def making_children(parents, population_size):
    children = []
    for _ in range(population_size):
        idx = np.random.choice(len(parents), size=2, replace=False)
        parent_1 = parents[idx[0]]
        parent_2 = parents[idx[1]]
        child = crossover(parent_1, parent_2)
        children.append(child)
    children = np.asarray(children)
    return children

def mutation(chromosomes_t, mutation_rate):
    chromosomes = chromosomes_t
    for chromosome in chromosomes:
        for i in range(len(chromosome)):
            if random.random() < mutation_rate:
                chromosome[i] = 1 if chromosome[i] == 0 else 0
    return chromosomes

In [ ]:
population_size = 50
n = 5
mutation_rate = 0.1
n_iteration = 1000

chromosomes = init(population_size)
for iteration in range(n_iteration):
    fitness_by_value = compute_fitness(chromosomes, 0)
    fitness_by_weight = compute_fitness(chromosomes, 1)
    top_n_by_value = select_top_n(chromosomes, fitness_by_value, population_size/2)
    top_n_by_weight = select_top_n(chromosomes, fitness_by_weight, population_size/2)
    parents_group_value = selection_within_subgroup(top_n_by_value, n)
    parents_group_weight = selection_within_subgroup(top_n_by_weight, n)
    parents = np.concatenate((parents_group_value, parents_group_weight), axis=0)
    chromosomes = making_children(parents, population_size)
    chromosomes = mutation(chromosomes, mutation_rate)
    
    # stat
    

In [42]:
 np.random.randint(2)

1

In [25]:
x = np.random.randint(10, size=10)
x

array([1, 3, 7, 1, 0, 2, 3, 2, 1, 9])

In [43]:
y = np.random.randint(10, size=10)
y

array([6, 3, 1, 9, 3, 4, 9, 1, 4, 9])

In [45]:
np.concatenate((x,y))

array([1, 3, 7, 1, 0, 2, 3, 2, 1, 9, 6, 3, 1, 9, 3, 4, 9, 1, 4, 9])

In [27]:
np.argsort(x)

array([4, 0, 3, 8, 5, 7, 1, 6, 2, 9], dtype=int64)

In [37]:
idx = np.argsort(-x)
idx

array([9, 2, 1, 6, 5, 7, 0, 3, 8, 4], dtype=int64)

In [40]:
idx[:3]

array([9, 2, 1], dtype=int64)

In [41]:
x[idx[:3]]

array([9, 7, 3])

In [19]:
x = init

In [22]:
x = 5
sum = x
sum

5

In [18]:
init(5)

[array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0]),
 array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 1, 1, 0, 